# Generated by Django 5.2.7 on 2025-10-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='emil',
            new_name='email',
        ),
    ]
