# Generated by Django 5.2.7 on 2025-10-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='userm',
            new_name='user',
        ),
    ]
